title: Fraction Maths Game
description: A level computer science project
email: help@roryclaasen.me

author: Rory Claasen
author_url: "http://roryclaasen.me"

url: "http://roryclaasen.me/computing-project"
base_url: "/computing-project"

compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  startings: [html, head, body]

sass:
   sass_dir: static/assets/styles
   style: :compressed

include: ['static', 'pubspec.yaml', 'LICENSE', 'README.md']
exclude: ['.gitignore', 'bin/', 'scripts/', 'build/', 'vendor', 'packages/', 'dart']
