title: Prototype
email: help@roryclaasen.me
description: A level computer science project
url: "http://roryclaasen.me/computing-project"
base_url: "/computing-project"
permalink: "/:title"

compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  startings: [html, head, body]

sass:
   sass_dir: web/assets/styles
   style: :compressed

# Making _site only have what is needed
include: ['web', 'pubspec.yaml', 'LICENSE', 'README.md']
exclude: ['.gitignore', 'bin', 'scripts', 'build', 'vendor', 'packages']
