title: Prototype
email: help@roryclaasen.me
description: A level computer science project
url: "http://roryclaasen.me/computing-project"

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
   sass_dir: web/styles
   style: :compressed

# Making _site only have what is needed
include: ['web', 'pubspec.yaml', 'LICENSE', 'README.md']
exclude: ['.gitignore', 'bin', 'scripts', 'build', 'vendor']
