title: Fraction Maths Game
description: A level computer science project
email: help@roryclaasen.me

author: Rory Claasen
author_url: "http://roryclaasen.me"

url_dir: "computing-project"

compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  startings: [html, head, body]

sass:
   sass_dir: site/assets/styles
   style: :compressed

include: ['site', 'pubspec.yaml', 'LICENSE', 'README.md']
exclude: ['.gitignore', 'bin', 'scripts', 'build', 'vendor', 'packages', 'database', 'src', 'links.md']
