title: Fraction Maths Game
description: A level computer science project
email: help@roryclaasen.me

source: "public"

author: Rory Claasen
author_url: "http://roryclaasen.me"

url_dir: "computing-project"

compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  startings: [html, head, body]

sass:
   sass_dir: assets/styles
   style: :compressed
