name: Computer_Science_Project
description: Rory Claasen's A Level Computer Science project.
version: 0.0.1
homepage: https://github.com/GOGO98901/computing-project
environment:
  sdk: '>=1.0.0'

dependencies:
  json_object: ^1.0.19
  dart_to_js_script_rewriter: "^1.0.1"
  browser: any
  yaml: any
  sass: any

transformers:
- dart_to_js_script_rewriter
- $dart2js:
    minify: true
    commandLineOptions: [--enable-experimental-mirrors]
- sass:
   style: compressed
